### ISSUE TITLE
Rubygems is pointing on wrong version of library on Rocky 9

### ISSUE THREAD

**Issue by trusnak** [sass-contrib/sass-embedded-host-ruby#187]
While I'm trying to install sass-embeded gem from rubygems on Rocky linux 9 it is fetching version for android, like this:
 ```
gem install sass-embedded
Fetching google-protobuf-3.25.3-x86_64-linux.gem
Successfully installed google-protobuf-3.25.3-x86_64-linux
Fetching sass-embedded-1.71.1-x86_64-linux-android.gem
Successfully installed sass-embedded-1.71.1-x86_64-linux-android
Parsing documentation for google-protobuf-3.25.3-x86_64-linux
Installing ri documentation for google-protobuf-3.25.3-x86_64-linux
Parsing documentation for sass-embedded-1.71.1-x86_64-linux-android
Installing ri documentation for sass-embedded-1.71.1-x86_64-linux-android
Done installing documentation for google-protobuf, sass-embedded after 1 seconds
2 gems installed
```
with bundler-2.5.6 it will fail completely:
```
Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/sass-embedded-1.70.0-x86_64-linux.gem)
Retrying download gem from https://rubygems.org/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/sass-embedded-1.70.0-x86_64-linux.gem)
Retrying download gem from https://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/sass-embedded-1.70.0-x86_64-linux.gem)
Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to
underlying error <bad response Forbidden 403
(https://rubygems.org/gems/sass-embedded-1.70.0-x86_64-linux.gem)>

/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/rubygems_integration.rb:459:in
`rescue in download_gem'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/rubygems_integration.rb:434:in
`download_gem'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:488:in
`download_gem'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:449:in
`fetch_gem'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:433:in
`fetch_gem_if_possible'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/source/rubygems.rb:162:in
`install'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:132:in
`do_install'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/installer/parallel_installer.rb:123:in
`block in worker_pool'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/worker.rb:62:in
`apply_func'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/worker.rb:57:in `block in
process_queue'
  /usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in `loop'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/worker.rb:54:in
`process_queue'
/usr/local/share/gems/gems/bundler-2.5.6/lib/bundler/worker.rb:90:in `block (2
levels) in create_threads'
```
According version available on rubygems it should download `https://rubygems.org/gems/sass-embedded-1.70.0-x86_64-linux-gnu.gem`, instead of `https://rubygems.org/gems/sass-embedded-1.70.0-x86_64-linux.gem`. Isn't it?

**Comment by ntkme** [comment]
Yes, it should download `-gnu` for glibc-based linux distribution. This is a well known bug in older versions of bundler/rubygems. You need **both** rubygems >=3.3.22 and bundler >=2.3.22. Given that you're running bundler 2.5.6, it's likely your rubygems is too old.

Please see discussion on: https://github.com/sass-contrib/sass-embedded-host-ruby/issues/176, that issue was happening on debian unstable, but essentially the root cause was the same.

**Comment by ntkme** [comment]
In general, the steps to fix the issue is:

``` sh
# Update to latest rubygems 
gem update --system
# Remove corrupted Gemfile.lock if any (if the file contains `-linux` instead of `-linux-gnu`)
rm Gemfile.lock
# Retry bundle install 
bundle
```

For certain vendor provided ruby, it might be impossible to upgrade rubygems. In that case it is recommended to have a separate ruby installation. You can use RVM, container, etc. The recommendation is to use ruby >=3.2, as the default rubygems/bundler come with ruby 3.2 or higher will work out of box.

**Comment by trusnak** [comment]
Thank you. I will try new  ruby-gems.

st 28. 2. 2024 v 20:42 odesílatel なつき ***@***.***> napsal:

**Comment by trusnak** [comment]
I got same error with:

- ruby-3.1.2
- rubygems-3.5.6
- bundler-2.5.6

```
01 /usr/bin/rbenv exec bundle install --jobs 4 --quiet
01 Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::Fe…
01 Retrying download gem from https://rubygems.org/ due to error (3/4): Gem::RemoteFetcher::Fe…
01 Retrying download gem from https://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::Fe…
01 Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to
01 underlying error <bad response Forbidden 403
01 (https://rubygems.org/gems/sass-embedded-1.71.1-x86_64-linux.gem)>
01
01 /var/www/novekocrm/shared/bundle/ruby/3.1.0/gems/bundler-2.5.6/lib/bundler/rubygems_integra…
01 `rescue in download_gem'
```

**Comment by ntkme** [comment]
Have you deleted `Gemfile.lock`?

**Comment by trusnak** [comment]
Yes, I did, and run bundle install.

čt 29. 2. 2024 v 18:20 odesílatel なつき ***@***.***> napsal:

**Comment by ntkme** [comment]
Can you please provide the output of executing the following:
``` sh
/usr/bin/rbenv exec bundle --version

/usr/bin/rbenv exec gem --version

/usr/bin/rbenv exec ruby -e 'puts Gem::Platform.new("x86_64-linux-gnu")'
```

**Comment by trusnak** [comment]
```
# /usr/bin/rbenv exec bundle --version
Bundler version 2.5.6
# /usr/bin/rbenv exec gem --version
3.2.33
# /usr/bin/rbenv exec ruby -e 'puts Gem::Platform.new("x86_64-linux-gnu")'
x86_64-linux
```

**Comment by trusnak** [comment]
That output from Gem::Platform looks bad, I think.

**Comment by ntkme** [comment]
Yeah, your `gem --version` is too old. As I said it has to be `>=3.3.22`.

**Comment by trusnak** [comment]
Sorry, my fault. Everything is working with 3.1.2 after rubygems updated to 3.5.6.
