### ISSUE TITLE
sass-embedded `Resource temporarily unavailable` under JRuby with Java 21

### ISSUE THREAD

**Issue by chadlwilson** [sass-contrib/sass-embedded-host-ruby#208]
Apologies for another vague issue - would appreciate if someone can point me in the right direction to debug this.

When building/running sass-embedded under JRuby with Java 21 something seems to not be working. When trying to compile assets (with sprockets) things hang and we get `writeFrom failed, path = '' (OS Error: Resource temporarily unavailable, errno = 35)` like the below.

Same code/scripting works fine under Java 17 with everything else the same.

This might be a JRuby issue, a sprockets issue, a google-protobuf (java) issue, a `sassc-embedded` issue or any number of other possible root causes. Please feel free to point me in the right direction to debug this further.

* MacOS Sonoma 14.5
* JRuby `9.4.7.0` (compatible Ruby `3.1.4`)
* Java `21.0.3+9.0.LTS`
* sass-embedded `1.77.1` (`Gemfile.lock` is [here](https://github.com/gocd/gocd/blob/23a9e0861af467690fcd910506c987a7c10cc1aa/server/src/main/webapp/WEB-INF/rails/Gemfile.lock))

Am essentially running a `rake --trace assets:clobber assets:precompile`

```
Fetching tzinfo-data 1.2024.1
Fetching activesupport 6.1.7.7
Fetching net-imap 0.4.11
Installing activesupport 6.1.7.7
Installing net-imap 0.4.11
Installing tzinfo-data 1.2024.1
Fetching net-pop 0.1.2
Installing net-pop 0.1.2
Installing nokogiri 1.16.5 (java)
Fetching net-smtp 0.5.0
Installing net-smtp 0.5.0
Fetching google-protobuf 4.26.1 (java)
Fetching rspec_junit_formatter 0.6.0
Installing rspec_junit_formatter 0.6.0
Fetching mail 2.8.1
Installing mail 2.8.1
Fetching globalid 1.2.1
Fetching activemodel 6.1.7.7
Installing google-protobuf 4.26.1 (java) with native extensions
Installing globalid 1.2.1
Fetching activejob 6.1.7.7
Fetching rails-dom-testing 2.2.0
Installing activemodel 6.1.7.7
Installing rails-dom-testing 2.2.0
Installing activejob 6.1.7.7
Fetching loofah 2.22.0
Fetching xpath 3.2.0
Fetching activerecord 6.1.7.7
Installing loofah 2.22.0
Installing xpath 3.2.0
Fetching rails-html-sanitizer 1.6.0
Fetching capybara 3.40.0
Installing activerecord 6.1.7.7
Installing rails-html-sanitizer 1.6.0
Fetching actionview 6.1.7.7
Installing capybara 3.40.0
Installing actionview 6.1.7.7
Fetching actionpack 6.1.7.7
Installing actionpack 6.1.7.7
Fetching activestorage 6.1.7.7
Fetching actioncable 6.1.7.7
Fetching actionmailer 6.1.7.7
Installing actionmailer 6.1.7.7
Installing actioncable 6.1.7.7
Installing activestorage 6.1.7.7
Fetching railties 6.1.7.7
Fetching sprockets-rails 3.4.2
Fetching rails-controller-testing 1.0.5
Installing sprockets-rails 3.4.2
Installing rails-controller-testing 1.0.5
Installing railties 6.1.7.7
Fetching actionmailbox 6.1.7.7
Installing actionmailbox 6.1.7.7
Fetching actiontext 6.1.7.7
Installing actiontext 6.1.7.7
Fetching js-routes 1.4.14
Fetching rspec-rails 6.1.2
Fetching rails 6.1.7.7
Installing rails 6.1.7.7
Installing rspec-rails 6.1.2
Installing js-routes 1.4.14
Fetching ts_routes 1.0.3
Installing ts_routes 1.0.3
Fetching sass-embedded 1.77.1
Installing sass-embedded 1.77.1 with native extensions
Fetching sassc-embedded 1.76.0
Installing sassc-embedded 1.76.0
Fetching dartsass-sprockets 3.1.0
Installing dartsass-sprockets 3.1.0
Bundle complete! 10 Gemfile dependencies, 71 gems now installed.
Bundled gems are installed into `./gems`
** Invoke assets:clobber (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:clobber
I, [2024-05-14T12:22:35.955379 #10399]  INFO -- : Removed /gocd/gocd/server/src/main/webapp/WEB-INF/rails/public/assets
** Invoke assets:precompile (first_time)
** Invoke assets:environment
** Execute assets:precompile
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: Unhandled exception:
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: FileSystemException: writeFrom failed, path = '' (OS Error: Resource temporarily unavailable, errno = 35)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:905)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:309)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #5      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #6      _StreamController._add (dart:async/stream_controller.dart:658)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #7      _StreamController.add (dart:async/stream_controller.dart:606)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #8      _StreamSinkImpl.add (dart:io/io_sink.dart:154)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #9      _StdSink.add (dart:io/stdio.dart:350)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #10     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #14     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #15     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #16     lengthDelimitedEncoder.<anonymous closure> (package:sass/src/embedded/util/length_delimited_transformer.dart:107)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #17     _HandlerEventSink.add (dart:async/stream_transformers.dart:209)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #18     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #22     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #23     _StreamController._add (dart:async/stream_controller.dart:658)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #24     _StreamController.add (dart:async/stream_controller.dart:606)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #25     _StreamTransformerWrapperSink.add (package:async/src/stream_sink_transformer/stream_transformer_wrapper.dart:49)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #26     DelegatingStreamSink.add (package:async/src/delegate/stream_sink.dart:35)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #31     _StreamController._add (dart:async/stream_controller.dart:658)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #32     _StreamController.add (dart:async/stream_controller.dart:606)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #33     _StreamSinkWrapper.add (dart:async/stream_controller.dart:876)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #34     ReusableIsolate.checkOut.<anonymous closure> (package:sass/src/embedded/reusable_isolate.dart:96)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #39     _StreamController._add (dart:async/stream_controller.dart:658)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #40     _StreamController.add (dart:async/stream_controller.dart:606)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: #41     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
/gocd/gocd/server/src/main/webapp/WEB-INF/rails/gems/jruby/3.1.0/gems/sass-embedded-1.77.1/lib/sass/compiler/connection.rb:56: warning: Attempt:11 waiting for isolate vm-isolate to check in
.............
```

**Comment by ntkme** [comment]
I have to take a more detailed look but most likely JDK21 + JRuby issue with stdio handling in the `open3` gem.

The code path that Dart VM ran into issue is where it’s trying to write its stdout to send response back to Ruby side. - This means at least the Dart VM received the request properly, so that sprockets, sassc-embedded, sass-embedded, and protobuf are all likely working.

The stdout of a child process can get stuck if the polling thread from the parent process is not working properly. It the stdout pipe buffer is completely full, and the parent process is not consuming the buffer at all, the whole child process can get stuck.

**Comment by ntkme** [comment]
@chadlwilson Also, was it on windows or unix-like, or both? JRuby has different I/O implementation for open3 on windows and unix-like.

**Comment by chadlwilson** [comment]
This was on MacOS Sonoma `14.5` (sorry, updated description) but I can give it a go on Linux if that helps (sounds like probably roughly the same behaviour expected though?).

I haven't yet attempted on Windows; usually that's the "final frontier" :D

**Comment by chadlwilson** [comment]
Hmm, could it be https://github.com/jruby/jruby/issues/8235 or https://github.com/jruby/jruby/issues/8069 ?

**Comment by ntkme** [comment]
I can reproduce this in CI with the following code:

``` ruby
    10000.times do |i|
      Sass.compile_string('a{b:c}' * i).css
      puts i
    end
```

On windows it works to the end. However on unix-like, this works until the 4368th iteration but fails at the 4369th iteration.

On the 4368th iteration, the size of protobuf reply message is 65530 bytes, and on the 4369th iteration the size of reply message is 65545 bytes.

``` ruby
require 'sass-embedded'

Sass.compile_string('a{b:c}' * 4368).css # works, stdout reply size is 65530 bytes
Sass.compile_string('a{b:c}' * 4369).css # fails, stdout reply size is 65545 bytes.
```

It must be https://github.com/jruby/jruby/issues/8235.

**Comment by chadlwilson** [comment]
OK, will close this for now and track there. Thanks for the effort, as always!

**Comment by chadlwilson** [comment]
I tried to monkey patch the `Connection` class and streams as in https://github.com/jruby/jruby/issues/8235#issuecomment-2109366836 but my Ruby and monkey-patching abilities are probably a bit too limited for that one :)

**Comment by ntkme** [comment]
``` ruby
# frozen_string_literal: true

require 'fcntl'

module Open3
  _popen_run = instance_method(:popen_run)
  define_method(:popen_run) do |cmd, opts, child_io, parent_io, &block|
    child_io.each do |io|
      flags = io.fcntl(Fcntl::F_GETFL)
      io.fcntl(Fcntl::F_SETFL, flags | (Fcntl::O_NONBLOCK))
      io.fcntl(Fcntl::F_SETFL, flags & (~Fcntl::O_NONBLOCK))
    end
    _popen_run.bind(self).call(cmd, opts, child_io, parent_io, &block)
  end
  module_function :popen_run
  class << self
    private :popen_run
  end
end
```

**Comment by chadlwilson** [comment]
Works like a dream! Didn't think of trying to monkey patch `popen` directly.

**Comment by ntkme** [comment]
It's the `child_io` who needs to be patched, rather than the `parent_io`. The return value of `popen3` is `parent_io`. Therefore, `popen3` has to be patched internally.
